# Generated by Django 4.2 on 2025-04-01 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='address',
        ),
        migrations.RemoveField(
            model_name='course',
            name='bathrooms',
        ),
        migrations.RemoveField(
            model_name='course',
            name='bedrooms',
        ),
        migrations.RemoveField(
            model_name='course',
            name='clubhouse',
        ),
        migrations.RemoveField(
            model_name='course',
            name='estate_size',
        ),
        migrations.RemoveField(
            model_name='course',
            name='price',
        ),
        migrations.RemoveField(
            model_name='course',
            name='sqft',
        ),
        migrations.RemoveField(
            model_name='course',
            name='street',
        ),
        migrations.AddField(
            model_name='course',
            name='classsize',
            field=models.IntegerField(default=''),
        ),
        migrations.AddField(
            model_name='course',
            name='coursecode',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='course',
            name='coursefee',
            field=models.IntegerField(default=''),
        ),
        migrations.AddField(
            model_name='course',
            name='demo',
            field=models.URLField(default='https://example.com', max_length=500),
        ),
        migrations.AddField(
            model_name='course',
            name='durationhr',
            field=models.DecimalField(decimal_places=1, default='', max_digits=2),
        ),
        migrations.AddField(
            model_name='course',
            name='studentreq',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='topic',
            field=models.CharField(choices=[('Islands', 'Islands'), ('Kwai Tsing', 'Kwai Tsing'), ('Sai Kung', 'Sai Kung'), ('Tsuen Wan', 'Tsuen Wan'), ('Tuen Mun ', 'Tuen Mun'), ('Yuen Long', 'Yuen Long'), ('Wong Tai Sin', 'Wong Tai Sin'), ('Sha Tin', 'Sha Tin'), ('Tai Po', 'Tai Po'), ('Kowloon City', 'Kowloon City'), ('Kwun Tong', 'Kwun Tong'), ('Sham Shui Po', 'Sham Shui Po'), ('Yau Tsim Mong', 'Yau Tsim Mong'), ('Central & Western', 'Central & Western'), ('Eastern', 'Eastern'), ('Southern', 'Southern'), ('Wan Chai', 'Wan Chai'), ('North', 'North')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='tutor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='tutors.tutor'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
