# Generated by Django 4.2 on 2025-04-11 01:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_photo', models.ImageField(upload_to='experience/photos/main/')),
                ('photo_1', models.ImageField(blank=True, null=True, upload_to='experience/photos/')),
                ('photo_2', models.ImageField(blank=True, null=True, upload_to='experience/photos/')),
                ('photo_3', models.ImageField(blank=True, null=True, upload_to='experience/photos/')),
                ('photo_4', models.ImageField(blank=True, null=True, upload_to='experience/photos/')),
                ('photo_5', models.ImageField(blank=True, null=True, upload_to='experience/photos/')),
                ('photo_6', models.ImageField(blank=True, null=True, upload_to='experience/photos/')),
                ('social_link', models.URLField(blank=True, help_text='YouTube/Instagram/Facebook URL', max_length=500, null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('event_date', models.DateTimeField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['event_date'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('video_file', models.FileField(upload_to='experience/videos/')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
