# Generated by Django 5.2 on 2025-04-14 18:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('exhibition', 'Exhibition'), ('competition', 'Competition'), ('workshop', 'Workshop')], default='workshop', max_length=50)),
                ('main_photo', models.ImageField(blank=True, null=True, upload_to='experience/photos/main/')),
                ('photo_1', models.ImageField(blank=True, null=True, upload_to='experience/photos/')),
                ('photo_2', models.ImageField(blank=True, null=True, upload_to='experience/photos/')),
                ('photo_3', models.ImageField(blank=True, null=True, upload_to='experience/photos/')),
                ('photo_4', models.ImageField(blank=True, null=True, upload_to='experience/photos/')),
                ('photo_5', models.ImageField(blank=True, null=True, upload_to='experience/photos/')),
                ('photo_6', models.ImageField(blank=True, null=True, upload_to='experience/photos/')),
                ('social_link', models.URLField(blank=True, help_text='YouTube/Instagram/Facebook URL', max_length=500, null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('event_date', models.DateField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['event_date'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('video_thumbnail', models.ImageField(blank=True, null=True, upload_to='experience/making_video/thumbnails/')),
                ('youtube_link', models.URLField(blank=True, help_text='YouTube link', max_length=500, null=True)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
