# Generated by Django 4.2 on 2025-04-11 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timelineevent',
            name='main_photo',
        ),
        migrations.RemoveField(
            model_name='timelineevent',
            name='photo_1',
        ),
        migrations.RemoveField(
            model_name='timelineevent',
            name='photo_2',
        ),
        migrations.RemoveField(
            model_name='timelineevent',
            name='photo_3',
        ),
        migrations.RemoveField(
            model_name='timelineevent',
            name='photo_4',
        ),
        migrations.RemoveField(
            model_name='timelineevent',
            name='photo_5',
        ),
        migrations.RemoveField(
            model_name='timelineevent',
            name='photo_6',
        ),
        migrations.RemoveField(
            model_name='timelineevent',
            name='social_link',
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='event_type',
            field=models.CharField(choices=[('type1', 'Type 1'), ('type2', 'Type 2'), ('type3', 'Type 3')], default='type1', max_length=5),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='icon_class',
            field=models.CharField(choices=[('lni-cake', 'Cake'), ('lni-burger', 'Burger'), ('lni-slim', 'Exercise')], default='lni-cake', max_length=20),
        ),
    ]
