# Generated by Django 4.2 on 2025-04-11 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0002_remove_timelineevent_main_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timelineevent',
            name='icon_class',
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='main_photo',
            field=models.ImageField(blank=True, null=True, upload_to='experience/photos/main/'),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='photo_1',
            field=models.ImageField(blank=True, null=True, upload_to='experience/photos/'),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='photo_2',
            field=models.ImageField(blank=True, null=True, upload_to='experience/photos/'),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='photo_3',
            field=models.ImageField(blank=True, null=True, upload_to='experience/photos/'),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='photo_4',
            field=models.ImageField(blank=True, null=True, upload_to='experience/photos/'),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='photo_5',
            field=models.ImageField(blank=True, null=True, upload_to='experience/photos/'),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='photo_6',
            field=models.ImageField(blank=True, null=True, upload_to='experience/photos/'),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='social_link',
            field=models.URLField(blank=True, help_text='YouTube/Instagram/Facebook URL', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='event_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='event_type',
            field=models.CharField(choices=[('exhibition', 'Exhibition'), ('competition', 'Competition'), ('workshop', 'Workshop')], default='workshop', max_length=50),
        ),
    ]
