# Generated by Django 4.2 on 2025-04-11 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0004_remove_timelineevent_main_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelineevent',
            name='main_photo',
            field=models.ImageField(blank=True, null=True, upload_to='experience/photos/main/'),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='photo_1',
            field=models.ImageField(blank=True, null=True, upload_to='experience/photos/'),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='photo_2',
            field=models.ImageField(blank=True, null=True, upload_to='experience/photos/'),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='photo_3',
            field=models.ImageField(blank=True, null=True, upload_to='experience/photos/'),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='photo_4',
            field=models.ImageField(blank=True, null=True, upload_to='experience/photos/'),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='photo_5',
            field=models.ImageField(blank=True, null=True, upload_to='experience/photos/'),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='photo_6',
            field=models.ImageField(blank=True, null=True, upload_to='experience/photos/'),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='social_link',
            field=models.URLField(blank=True, help_text='YouTube/Instagram/Facebook URL', max_length=500, null=True),
        ),
    ]
