# Generated by Django 5.2 on 2025-04-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0005_timelineevent_main_photo_timelineevent_photo_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_file',
        ),
        migrations.AddField(
            model_name='video',
            name='video_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='experience/making_video/thumbnails/'),
        ),
        migrations.AddField(
            model_name='video',
            name='youtube_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='event_type',
            field=models.CharField(choices=[('exhibition', '展覽'), ('competition', '比賽'), ('workshop', '工作坊及作品製作')], default='workshop', max_length=50),
        ),
    ]
