# Generated by Django 5.2 on 2025-04-13 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0005_timelineevent_main_photo_timelineevent_photo_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_file',
        ),
        migrations.AddField(
            model_name='video',
            name='video_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='experience/making_video/thumbnails/'),
        ),
        migrations.AddField(
            model_name='video',
            name='youtube_link',
            field=models.URLField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
