# Generated by Django 5.2 on 2025-04-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0006_remove_video_video_file_video_video_thumbnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelineevent',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
