# Generated by Django 5.2 on 2025-04-14 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0007_timelineevent_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timelineevent',
            name='slug',
        ),
    ]
